
version: '3.1'
services:

  web:
    image: nginx
    restart: always
    container_name: nginx
    volumes:
      - ./etc/nginx:/etc/nginx
      - ./usr/share/nginx:/usr/share/nginx
    ports:
      - "81:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  blog:
    image: halohub/halo
    restart: always
    container_name: myhalo
    ports: 
      - 8090:8090
      - 1024:8090
    volumes: 
      - ~/.halo:/root/.halo

